library(tm)
library(wordcloud)
library(Rgraphviz)
library(RColorBrewer)
library(wordcloud)
library(topicmodels)
library(plyr)
library(ggplot2)
library(RTextTools)
library(e1071)

x <- load_tweets_db(as.data.frame = TRUE, table_name = "programminglanguages")