training_data <- read.table("./UCI HAR Dataset/train/X_train.txt")
training_labels <- read.table("./UCI HAR Dataset/train/y_train.txt")
pairs(training_data[,0:10])
print(dim(training_data))
print(dim(training_labels))
